import { Tool, ToolCategory, ToolCategoryConfig } from '@/types/tools';

export const toolCategories: Record<ToolCategory, ToolCategoryConfig> = {
  css: {
    name: 'CSS & Visual',
    icon: 'Palette',
    slug: 'css',
    description: 'Generate beautiful CSS styles, gradients, shadows, and more',
  },
  converters: {
    name: 'Converters',
    icon: 'ArrowLeftRight',
    slug: 'converters',
    description: 'Convert between different formats and languages',
  },
  utilities: {
    name: 'Utilities',
    icon: 'Wrench',
    slug: 'utilities',
    description: 'Handy utilities for everyday development tasks',
  },
  tailwind: {
    name: 'Tailwind CSS',
    icon: 'Wind',
    slug: 'tailwind',
    description: 'Tools specifically designed for Tailwind CSS workflows',
  },
} as const;

export const tools: Tool[] = [
  // CSS & Visual Tools
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients with modern color spaces and Tailwind export',
    category: 'css',
    path: '/tools/gradient-generator',
    icon: 'Paintbrush',
    isNew: true,
    keywords: ['gradient', 'css', 'background', 'linear', 'radial', 'conic'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes with accessibility checks',
    category: 'css',
    path: '/tools/color-palette',
    icon: 'Palette',
    isNew: true,
    keywords: ['color', 'palette', 'harmony', 'complementary', 'analogous'],
  },
  {
    id: 'shadow-generator',
    name: 'Shadow Generator',
    description: 'Create layered box shadows with CSS and Tailwind output',
    category: 'css',
    path: '/tools/shadow-generator',
    icon: 'Square',
    keywords: ['shadow', 'box-shadow', 'css', 'drop-shadow'],
  },
  {
    id: 'border-radius',
    name: 'Border Radius Generator',
    description: 'Design custom border radius with asymmetric corners',
    category: 'css',
    path: '/tools/border-radius',
    icon: 'RectangleHorizontal',
    keywords: ['border', 'radius', 'rounded', 'corners'],
  },
  {
    id: 'sprite-css',
    name: 'Sprite CSS Generator',
    description: 'Extract CSS from sprite sheets with visual selection',
    category: 'css',
    path: '/tools/sprite-css',
    icon: 'Grid3X3',
    isNew: true,
    keywords: ['sprite', 'spritesheet', 'css', 'background-position', 'image'],
  },

  // Converter Tools
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON to TypeScript interfaces and types',
    category: 'converters',
    path: '/tools/json-to-typescript',
    icon: 'FileJson',
    isNew: true,
    keywords: ['json', 'typescript', 'interface', 'types', 'convert'],
  },
  {
    id: 'css-to-tailwind',
    name: 'CSS to Tailwind',
    description: 'Convert CSS styles to Tailwind utility classes',
    category: 'converters',
    path: '/tools/css-to-tailwind',
    icon: 'Code',
    keywords: ['css', 'tailwind', 'convert', 'classes'],
  },
  {
    id: 'svg-to-react',
    name: 'SVG to React',
    description: 'Convert SVG to React/JSX components with TypeScript support',
    category: 'converters',
    path: '/tools/svg-to-react',
    icon: 'FileCode',
    keywords: ['svg', 'react', 'jsx', 'component', 'convert'],
  },
  {
    id: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert between CSS units: px, rem, em, pt, cm, mm, in, pc, vh, vw, %',
    category: 'converters',
    path: '/tools/css-unit-converter',
    icon: 'Ruler',
    keywords: ['css', 'unit', 'converter', 'px', 'rem', 'em', 'pt', 'cm', 'mm', 'in', 'pc', 'vh', 'vw', 'percent', 'pixels', 'convert'],
  },
  {
    id: 'css-letter-spacing',
    name: 'CSS Letter Spacing Calculator',
    description: 'Convert between percentage and pixel values for letter-spacing',
    category: 'converters',
    path: '/tools/css-letter-spacing',
    icon: 'Type',
    isNew: true,
    keywords: ['css', 'letter-spacing', 'typography', 'font', 'spacing', 'tracking', 'convert'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, RGBA, HSL, HSLA and more. Paste any format, see all equivalents and copy CSS snippets.',
    category: 'converters',
    path: '/tools/color-converter',
    icon: 'Droplets',
    isNew: true,
    keywords: ['color converter', 'hex to rgb', 'rgba to hex', 'hsl to hex', 'rgb to hex', 'color format', 'hex rgb hsl'],
  },

  // Utility Tools
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress JPEG, PNG, WebP, and AVIF images up to 80% smaller with smart optimization',
    category: 'utilities',
    path: '/tools/image-compressor',
    icon: 'ImageDown',
    isNew: true,
    keywords: [
      'compress image',
      'reduce image size',
      'image optimizer',
      'jpeg compression',
      'png compression',
      'webp',
      'avif',
      'batch compress',
      'image converter',
      'reduce file size',
      'optimize images',
      'compress photos',
    ],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching and explanations',
    category: 'utilities',
    path: '/tools/regex-tester',
    icon: 'Regex',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test'],
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with image support',
    category: 'utilities',
    path: '/tools/base64',
    icon: 'Binary',
    keywords: ['base64', 'encode', 'decode', 'image', 'data-url'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUIDs in bulk with version selection',
    category: 'utilities',
    path: '/tools/uuid-generator',
    icon: 'Fingerprint',
    keywords: ['uuid', 'guid', 'unique', 'identifier', 'generate'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text with dev-themed variants',
    category: 'utilities',
    path: '/tools/lorem-ipsum',
    icon: 'Type',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy'],
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate URL-safe slugs in multiple formats',
    category: 'utilities',
    path: '/tools/slug-generator',
    icon: 'Link',
    keywords: ['slug', 'url', 'kebab', 'snake', 'camel'],
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts and highlight the differences',
    category: 'utilities',
    path: '/tools/diff-checker',
    icon: 'FileDiff',
    keywords: ['diff', 'compare', 'difference', 'text', 'merge'],
  },

  // Tailwind Tools
  {
    id: 'tailwind-colors',
    name: 'Tailwind Color Shades',
    description: 'Generate full 50-950 color scale from any color',
    category: 'tailwind',
    path: '/tools/tailwind-colors',
    icon: 'Droplets',
    isNew: true,
    keywords: ['tailwind', 'color', 'shades', 'palette', 'scale'],
  },
  {
    id: 'tailwind-class-sorter',
    name: 'Tailwind Class Sorter',
    description: 'Sort Tailwind classes in recommended order',
    category: 'tailwind',
    path: '/tools/tailwind-class-sorter',
    icon: 'ArrowUpDown',
    keywords: ['tailwind', 'sort', 'order', 'classes', 'prettier'],
  },
  
  // New High-Traffic Tools
  {
    id: 'qr-code',
    name: 'QR Code Generator',
    description: 'Create custom QR codes with adjustable colors, size, and error correction',
    category: 'utilities',
    path: '/tools/qr-code',
    icon: 'QrCode',
    isNew: true,
    keywords: [
      'qr code',
      'qr generator',
      'qr code maker',
      'create qr code',
      'custom qr code',
      'qr code png',
      'qr code svg',
    ],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure passwords with customizable length and character types',
    category: 'utilities',
    path: '/tools/password-generator',
    icon: 'Lock',
    isNew: true,
    keywords: [
      'password generator',
      'strong password',
      'random password',
      'secure password',
      'password creator',
    ],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, and estimate reading time',
    category: 'utilities',
    path: '/tools/word-counter',
    icon: 'FileText',
    isNew: true,
    keywords: [
      'word counter',
      'character counter',
      'word count',
      'character count',
      'reading time',
      'text analysis',
    ],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes for text and files',
    category: 'utilities',
    path: '/tools/hash-generator',
    icon: 'Hash',
    isNew: true,
    keywords: [
      'hash generator',
      'md5',
      'sha256',
      'sha512',
      'checksum',
      'hash calculator',
    ],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates with timezone support',
    category: 'utilities',
    path: '/tools/timestamp-converter',
    icon: 'Clock',
    isNew: true,
    keywords: [
      'timestamp converter',
      'unix timestamp',
      'epoch converter',
      'timestamp to date',
      'date to timestamp',
    ],
  },
  {
    id: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate custom placeholder images with adjustable dimensions, colors, and text',
    category: 'utilities',
    path: '/tools/placeholder-image',
    icon: 'Image',
    isNew: true,
    keywords: [
      'placeholder image',
      'dummy image',
      'placeholder generator',
      'test image',
      'mockup image',
    ],
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown to HTML with live preview and GitHub-flavored markdown support',
    category: 'converters',
    path: '/tools/markdown-to-html',
    icon: 'FileCode',
    isNew: true,
    keywords: [
      'markdown to html',
      'md to html',
      'markdown converter',
      'markdown preview',
      'github markdown',
    ],
  },
  {
    id: 'code-minifier',
    name: 'Code Minifier',
    description: 'Minify HTML, CSS, and JavaScript to reduce file sizes and optimize performance',
    category: 'utilities',
    path: '/tools/code-minifier',
    icon: 'Minimize2',
    isNew: true,
    keywords: [
      'code minifier',
      'html minifier',
      'css minifier',
      'javascript minifier',
      'minify code',
      'compress code',
    ],
  },
  {
    id: 'code-formatter',
    name: 'Code Formatter',
    description: 'Format and beautify HTML, CSS, JavaScript, and JSON with Prettier',
    category: 'utilities',
    path: '/tools/code-formatter',
    icon: 'Sparkles',
    isNew: true,
    keywords: [
      'code formatter',
      'code beautifier',
      'prettier online',
      'format code',
      'beautify code',
    ],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text to uppercase, lowercase, title case, sentence case, camelCase, snake_case, and kebab-case',
    category: 'utilities',
    path: '/tools/case-converter',
    icon: 'Type',
    isNew: true,
    keywords: [
      'case converter',
      'text case',
      'uppercase',
      'lowercase',
      'title case',
      'camelCase',
      'snake_case',
      'kebab-case',
      'convert case',
    ],
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Build cron expressions visually. See human-readable description and next run times',
    category: 'utilities',
    path: '/tools/cron-generator',
    icon: 'Clock',
    isNew: true,
    keywords: [
      'cron generator',
      'crontab builder',
      'cron expression',
      'next run time',
      'schedule builder',
    ],
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicons in 16, 32, 48, and 180px from one image. Download PNG or ZIP',
    category: 'utilities',
    path: '/tools/favicon-generator',
    icon: 'Image',
    isNew: true,
    keywords: [
      'favicon generator',
      'favicon maker',
      'create favicon',
      'favicon sizes',
      'apple touch icon',
    ],
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by pixels or scale. Lock aspect ratio, optional center crop. All in browser',
    category: 'utilities',
    path: '/tools/image-resizer',
    icon: 'Image',
    isNew: true,
    keywords: [
      'image resizer',
      'resize image',
      'resize image online',
      'crop image',
      'image dimensions',
    ],
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Merge multiple PDFs into one file. Drag to reorder. All processing in your browser',
    category: 'utilities',
    path: '/tools/pdf-merger',
    icon: 'FileText',
    isNew: true,
    keywords: [
      'merge pdf',
      'combine pdf',
      'pdf merger',
      'pdf joiner',
      'merge pdf online free',
    ],
  },
  {
    id: 'css-animations',
    name: 'CSS Animation Generator',
    description: 'Create and customize popular CSS animations with live preview. Export to CSS, Tailwind, or copy-paste classes with full control over duration, timing, and effects.',
    category: 'css',
    path: '/tools/css-animations',
    icon: 'Sparkles',
    isNew: true,
    keywords: [
      'animation',
      'css',
      'keyframes',
      'animate',
      'transition',
      'motion',
      'effects',
      'tailwind animation',
      'css effects',
      'web animation',
    ],
  },
  // New high-traffic tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format and validate JSON with syntax highlighting. Minify, prettify, sort keys. All processing in your browser.',
    category: 'converters',
    path: '/tools/json-formatter',
    icon: 'FileJson',
    isNew: true,
    keywords: [
      'json formatter',
      'json validator',
      'format json online',
      'json prettifier',
      'json beautifier',
      'validate json',
      'json syntax checker',
    ],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT header and payload. View claims, expiration, issuer. All processing in your browser.',
    category: 'utilities',
    path: '/tools/jwt-decoder',
    icon: 'Key',
    isNew: true,
    keywords: [
      'jwt decoder',
      'jwt decode',
      'jwt token decoder',
      'decode jwt',
      'jwt debugger',
      'jwt payload viewer',
      'jwt header decoder',
    ],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components and full URLs. Parse query strings and path segments.',
    category: 'utilities',
    path: '/tools/url-encoder',
    icon: 'Link',
    isNew: true,
    keywords: [
      'url encoder',
      'url decoder',
      'url encode online',
      'percent encoding',
      'url encode decode',
      'uri encoder',
      'url parameter encoder',
    ],
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check WCAG contrast ratios for accessibility. Real-time preview and pass/fail for AA and AAA.',
    category: 'css',
    path: '/tools/contrast-checker',
    icon: 'Contrast',
    isNew: true,
    keywords: [
      'contrast checker',
      'wcag contrast',
      'color contrast checker',
      'accessibility checker',
      'contrast ratio calculator',
      'aa contrast checker',
      'aaa contrast',
    ],
  },
  {
    id: 'meta-tags',
    name: 'Meta Tag Generator',
    description: 'Generate meta tags for SEO and social sharing. Open Graph, Twitter Cards, and structured data.',
    category: 'utilities',
    path: '/tools/meta-tags',
    icon: 'FileCode',
    isNew: true,
    keywords: [
      'meta tag generator',
      'open graph generator',
      'twitter card generator',
      'seo meta tags',
      'og tags generator',
      'meta tags creator',
      'social media meta tags',
    ],
  },
  {
    id: 'escape-unescape',
    name: 'Escape/Unescape',
    description: 'Escape and unescape text for JSON, HTML, and URL. Handle special characters correctly.',
    category: 'utilities',
    path: '/tools/escape-unescape',
    icon: 'Shield',
    isNew: true,
    keywords: [
      'escape unescape',
      'html escape',
      'json escape',
      'url escape',
      'html encoder',
      'string escape',
      'escape special characters',
    ],
  },

  // Plan additions: Cron decoder, Text shadow, YAML↔JSON, HTTP status, Flexbox/Grid, CSV→JSON, .gitignore, Tailwind→CSS
  {
    id: 'cron-decoder',
    name: 'Cron Expression Decoder',
    description: 'Decode cron expressions. See human-readable description and next run times. Paste any 5-field cron.',
    category: 'utilities',
    path: '/tools/cron-decoder',
    icon: 'Clock',
    keywords: ['cron decoder', 'cron parser', 'decode cron', 'cron explain', 'next run time'],
  },
  {
    id: 'text-shadow-generator',
    name: 'Text Shadow Generator',
    description: 'Create layered text shadows with CSS and Tailwind export. Perfect for headings and hero text.',
    category: 'css',
    path: '/tools/text-shadow-generator',
    icon: 'Type',
    keywords: ['text shadow', 'css text-shadow', 'text shadow generator', 'tailwind drop-shadow'],
  },
  {
    id: 'yaml-json',
    name: 'YAML to JSON Converter',
    description: 'Convert YAML to JSON and JSON to YAML. For configs, CI, and docs. All in your browser.',
    category: 'converters',
    path: '/tools/yaml-json',
    icon: 'FileCode',
    keywords: ['yaml to json', 'json to yaml', 'yaml converter', 'yaml json'],
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Code Reference',
    description: 'Searchable reference of HTTP status codes with descriptions and typical use cases.',
    category: 'utilities',
    path: '/tools/http-status-codes',
    icon: 'FileText',
    keywords: ['http status codes', 'status code reference', '404', '500', 'rest api'],
  },
  {
    id: 'flexbox-grid-generator',
    name: 'Flexbox & Grid Generator',
    description: 'Visual layout builder for Flexbox and CSS Grid. Export CSS or Tailwind.',
    category: 'css',
    path: '/tools/flexbox-grid-generator',
    icon: 'LayoutGrid',
    keywords: ['flexbox generator', 'grid generator', 'css flex', 'css grid', 'layout builder'],
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV to JSON (array of objects). Custom delimiter and headers. For APIs and mock data.',
    category: 'converters',
    path: '/tools/csv-to-json',
    icon: 'FileJson',
    keywords: ['csv to json', 'csv converter', 'parse csv', 'csv parser'],
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files with checkboxes for OS, editors, languages, and frameworks.',
    category: 'utilities',
    path: '/tools/gitignore-generator',
    icon: 'FileCode',
    keywords: ['gitignore generator', 'git ignore', 'gitignore template'],
  },
  {
    id: 'tailwind-to-css',
    name: 'Tailwind to CSS',
    description: 'Convert Tailwind utility classes to equivalent CSS. Debug and understand Tailwind output.',
    category: 'tailwind',
    path: '/tools/tailwind-to-css',
    icon: 'Code',
    keywords: ['tailwind to css', 'tailwind converter', 'tailwind decode', 'utility to css'],
  },

  // PDF, converters, utilities (privacy-first, all in browser)
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to PNG or JPG images, or extract pages as separate PDFs. All processing in your browser—files never leave your device.',
    category: 'utilities',
    path: '/tools/pdf-to-image',
    icon: 'FileImage',
    keywords: ['pdf to image', 'pdf to png', 'pdf to jpg', 'extract pdf pages', 'pdf page extractor'],
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON to CSV for spreadsheets and data export. Paste JSON, get CSV. All in your browser.',
    category: 'converters',
    path: '/tools/json-to-csv',
    icon: 'FileJson',
    keywords: ['json to csv', 'convert json to csv', 'json csv converter'],
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML to Markdown. Paste HTML and get clean Markdown. All processing in your browser.',
    category: 'converters',
    path: '/tools/html-to-markdown',
    icon: 'FileCode',
    keywords: ['html to markdown', 'html to md', 'convert html to markdown'],
  },
  {
    id: 'html-entities',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode and decode HTML entities: named (&nbsp;, &copy;) and numeric (&#160;, &#x20;). Extends basic escape with full entity support.',
    category: 'utilities',
    path: '/tools/html-entities',
    icon: 'Shield',
    keywords: ['html entities', 'html entity encoder', 'html entity decoder', 'named entities', 'numeric entities'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Minify and optimize SVG files. Remove metadata, trim whitespace, reduce file size. All in your browser.',
    category: 'utilities',
    path: '/tools/svg-optimizer',
    icon: 'Image',
    keywords: ['svg optimizer', 'svg minifier', 'minify svg', 'optimize svg'],
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    description: 'Convert XML to JSON and JSON to XML. For APIs and configs. All processing in your browser.',
    category: 'converters',
    path: '/tools/xml-to-json',
    icon: 'FileCode',
    keywords: ['xml to json', 'convert xml to json', 'xml json converter'],
  },
  {
    id: 'user-agent-parser',
    name: 'User-Agent Parser',
    description: 'Parse User-Agent strings to see browser, OS, and device. Paste any UA string—all parsing in your browser.',
    category: 'utilities',
    path: '/tools/user-agent-parser',
    icon: 'Monitor',
    keywords: ['user agent parser', 'ua parser', 'parse user agent', 'browser detection'],
  },
];

// Helper functions
export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

/** Resolve tool by URL slug (slug === tool.id). Use in tools/[slug] route. */
export function getToolBySlug(slug: string): Tool | undefined {
  return getToolById(slug);
}

export function getToolByPath(path: string): Tool | undefined {
  return tools.find((tool) => tool.path === path);
}

/** Score relevance: name start (best) > name contains > description > keywords. */
function scoreToolMatch(tool: Tool, lowerQuery: string): number {
  const name = tool.name.toLowerCase();
  const desc = tool.description.toLowerCase();
  if (name.startsWith(lowerQuery)) return 4;
  if (name.includes(lowerQuery)) return 3;
  if (desc.includes(lowerQuery)) return 2;
  if (tool.keywords?.some((k) => k.toLowerCase().includes(lowerQuery))) return 1;
  return 0;
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  return tools
    .map((tool) => ({ tool, score: scoreToolMatch(tool, lowerQuery) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score || a.tool.name.localeCompare(b.tool.name))
    .map(({ tool }) => tool);
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}
